name: Publish

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '13.13.0'

      - name: Setup npm
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Install modules
        run: npm install

      - name: Build
        run: npm run package

      - name: Publish
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        run: npx vsce publish -p $VSCE_TOKEN
