name: Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '13.13.0'

      - name: Install modules
        run: npm install

      - name: Build
        run: npm run package

      - name: Publish
        env:
          VSCE_TOKEN: ${{secrets.VSCE_TOKEN}}
        run: vsce publish -p $VSCE_TOKEN
